after_success: coveralls
cache: pip
dist: xenial
install:
  - yes | pip uninstall py pytest
  - pip install coveralls flake8 pydocstyle sphinx sphinx_rtd_theme
  - python setup.py install
language: python
matrix:
  allow_failures:
    - python: nightly
  fast_finish: true
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
script:
  - flake8 --exclude=.eggs,build,docs
  - pydocstyle praw
  - sphinx-build -W docs/ /tmp/foo
  - coverage run --source=praw setup.py test
