name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        default: 'true'
        required: true
      days-before-stale:
        description: 'Number of days before marking as stale'
        default: '20'
        required: false
      days-before-close:
        description: 'Number of days before closing after being marked as stale'
        default: '10'
        required: false

env:
  stale-close-label: 'Auto-closed - Stale'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          debug-only: ${{ env.dry-run }}
          enable-statistics: true

          days-before-close: ${{ env.days-before-close }}
          days-before-stale: ${{ env.days-before-stale }}

          stale-issue-message: 'This issue is stale because it has been open for ${{ env.days-before-stale }} days with no activity. Remove the Stale label or comment or this will be closed in ${{ env.days-before-close }} days.'
          stale-pr-message: 'This PR is stale because it has been open for ${{ env.days-before-stale }} days with no activity. Remove the Stale label or comment or this will be closed in ${{ env.days-before-close }} days.'

          close-issue-message: 'This issue was closed because it has been stale for ${{ env.days-before-close }} days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for ${{ env.days-before-close }} days with no activity.'

          close-issue-label: ${{ env.stale-close-label }}
          close-pr-label: ${{ env.stale-close-label }}

          exempt-pr-labels: ${{ env.exempt-labels }}
          exempt-issue-labels: ${{ env.exempt-labels }}
